# Config file for automatic testing at travis-ci.org
dist: xenial
language: python

python: 3.7

stages:
  - test
  - deploy-to-production
  - test-production

jobs:
  include:
    - name: "Lint"
      script:
        - npm run lint
        - flask lint --check
        - pre-commit run --all-files
    - name: "Run unit tests"
      stage: test
      script: flask test
    - name: "Deploy to Heroku"
      if: branch = master
      stage: deploy-to-production
      before_script: skip
      script: skip
      deploy:
        provider: heroku
        app: $HEROKU_APP_NAME
        api_key: $HEROKU_AUTH_TOKEN
        on: master
    - name: "Test production"
      if: branch = master
      stage: test-production
      before_script: skip
      script: 'curl https://${HEROKU_APP_NAME}.herokuapp.com/'

before_script:
  - pip install -r requirements/dev.txt
  - nvm install 12
  - nvm use 12
  - npm install
  - cp .env.example .env
