version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.7
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules

services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "home_budgeting_app-development"
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
      - "2992:2992"
    command: "npm start"
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "home_budgeting_app-production"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: manage
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "home_budgeting_app-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

  postgres:
    image: postgres:11
    restart: always
    env_file:
      - .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  node-modules:
  static-build:
  local_postgres_data: {}
